<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
$helper = $this->helper('Hiddentechies\Bizkick\Helper\Data');
$showNewsletter = $helper->getConfigValue('bizkicksettings/newsletter_settings/enable');
$showFooterColumns = $helper->getConfigValue('bizkicksettings/footer_columns/enable_footer_columns');
$footerStColumnSelect = $helper->getConfigValue('bizkicksettings/footer_columns/footer_st_column_select');
$footerStColumn = $helper->getConfigValue('bizkicksettings/footer_columns/footer_st_column');
$footerNdColumn = $helper->getConfigValue('bizkicksettings/footer_columns/footer_nd_column');
$footerRdColumn = $helper->getConfigValue('bizkicksettings/footer_columns/footer_rd_column');
$address = $helper->getConfigValue('bizkicksettings/footer_contant/address');
$email = $helper->getConfigValue('bizkicksettings/footer_contant/email');
$phone = $helper->getConfigValue('bizkicksettings/footer_contant/phone');
$enableFooterBottom = $helper->getConfigValue('bizkicksettings/footer_bottom/enable_footer_bottom');
$copyrightText = $helper->getConfigValue('bizkicksettings/footer_bottom/copyright_text');
$copyrightRightBlock = $helper->getConfigValue('bizkicksettings/footer_bottom/copyright_right_block');
?>
<div class="footer-top">
    <?php if ($showNewsletter) { ?>
        <div class="footer-newsletter">
        <!-- <img class="footernewsletter" src="http://yourbetsy.com/pub/media/wysiwyg/images/footernewsletter.png" alt="footernewsletter" /> -->
            <div class="page-main">
                <?php echo $this->getChildHtml('form.subscribe'); ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($showFooterColumns) { ?>
        <div class="footer-links custom-footer-links">
            <div class="page-main">
                <div class="footer-links-main custom-footer-links-container">
                    <div class="footer-links-column custom-footer-col">
                        <?php if ($footerRdColumn != '') { ?>
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-help')->toHtml(); ?>
                        <?php } ?>
                    </div>
                    <div class="footer-links-column custom-footer-col">
                        <?php if ($footerNdColumn != '') { ?>
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerNdColumn)->toHtml(); ?>
                        <?php } ?>
                    </div>
                    <div class="footer-links-column custom-footer-col">
                        <?php if ($footerStColumnSelect == 'quicklinks') { ?>
                            <div class="footer-colum-title">
                                <h3>
                                    Quick Links
                                </h3>
                            </div>
                            <div class="footer-column-content">
                                <?php echo $this->getChildHtml('footer_links'); ?>
                            </div>
                        <?php } else { ?>
                            <?php if ($footerStColumn != '') { ?>
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerStColumn)->toHtml(); ?>
                            <?php } ?>
                        <?php } ?>
                    </div>
                    <div class="footer-links-column custom-footer-col">
                        <?php if ($enableFooterBottom) { ?>
                            <div class="copuright-outer">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-logo-icon-betsy')->toHtml(); ?>
                                    <small class="copyright">
                                        <span><?php /* @escapeNotVerified */ echo $copyrightText; ?></span>
                                    </small>
                                <?php if ($copyrightRightBlock != '') { ?>
                                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($copyrightRightBlock)->toHtml(); ?>
                                <?php } ?>
                            </div>
                        <?php } ?>
                        <?php if ($footerRdColumn != '') { ?>
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social-medial-link-fb-ins-tw')->toHtml(); ?>
                        <?php } ?>
                    </div>
                   
                </div>
            </div>
        </div>
    <?php } ?>
</div>
<script type="text/javascript" xml="space">
    require(['jquery'], function() {
        var windowWidth = jQuery(window).width();
        if (windowWidth < 768) {
            jQuery('.footer-links-column .footer-column-content').hide();
            jQuery(document).on('click', '.footer-links-column', function() {
                jQuery(this).addClass('active-column');
                jQuery(this).find('.footer-column-content').slideDown();
            });
            jQuery(document).on('click', '.footer-column-content', function(e) {
                e.preventdefault();
                return false;
            });
            jQuery(document).on('click', '.footer-links-column.active-column', function() {
                jQuery(this).removeClass('active-column');
                jQuery(this).find('.footer-column-content').slideUp();
            });
        }
    });
</script>